# Generated by Django 3.2.7 on 2023-06-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditsTableList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.IntegerField()),
                ('issueDate', models.DateField()),
                ('expiryDate', models.DateField(editable=False)),
            ],
        ),
    ]
