# Generated by Django 3.2.7 on 2023-06-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_list',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
